import type { CalendarRecord } from './types.js';

function escapeIcsText(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\r?\n/g, '\\n');
}

function formatIcsDate(iso: string | null): string | null {
  if (!iso) return null;
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return null;
  return date.toISOString().replace(/[-:]/g, '').replace(/\.\d{3}Z$/, 'Z');
}

export function calendarToIcs(records: CalendarRecord[], generatedAt = new Date()): string {
  const stamp = formatIcsDate(generatedAt.toISOString()) ?? '20260101T000000Z';
  const lines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//PANTHERA//World Cup 2026 Fixtures Actor//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'X-WR-CALNAME:World Cup 2026 Fixtures',
    'X-WR-CALDESC:FIFA World Cup 2026 fixtures generated by Apify Actor world-cup-2026-fixtures-schedule-api'
  ];

  for (const record of records) {
    const start = formatIcsDate(record.startsAtUtc);
    if (!start) continue;
    const endDate = new Date(record.startsAtUtc!);
    endDate.setHours(endDate.getHours() + 2);
    const end = formatIcsDate(endDate.toISOString()) ?? start;

    lines.push(
      'BEGIN:VEVENT',
      `UID:${escapeIcsText(record.uid)}`,
      `DTSTAMP:${stamp}`,
      `DTSTART:${start}`,
      `DTEND:${end}`,
      `SUMMARY:${escapeIcsText(record.title)}`,
      `DESCRIPTION:${escapeIcsText(`${record.description}\\nSource: ${record.sourceUrl}`)}`,
      `LOCATION:${escapeIcsText(record.location ?? 'World Cup 2026')}`,
      `URL:${escapeIcsText(record.sourceUrl)}`,
      'END:VEVENT'
    );
  }

  lines.push('END:VCALENDAR');
  return `${lines.join('\r\n')}\r\n`;
}
